### ISSUE TITLE
Player with specified name not found/No play time data stored at all.

### ISSUE THREAD

**Issue by NovaLynxie** [TheBrokenDown/PlayTimeCounter#5]
Hi there. I am having some difficulty with this plugin in getting it to record player's play time.
I have configured both the sponge and plugin configs correctly for this to work and got it to connect to the sql database, however it seems no data is being stored properly and therefore throws an error when running the /ptc command on player's client. Also tried running the command via server console and same error occured saying player was not found.
![PlayTimeCounter ptc cmd Error message](https://user-images.githubusercontent.com/21307676/104370598-03207680-5517-11eb-8449-21ce9c52f046.PNG)

Tried the ptctop command also and it says 'no data' for this at all.
![PlayTimeCounter ptc cmd No data for ptctop](https://user-images.githubusercontent.com/21307676/104370604-0451a380-5517-11eb-8da0-11758f74a783.PNG)

Not sure how often it checks but it simply acts as if its a brand new installation with no playtime data in the database.
The error that keeps coming up in the console is concerning. I have pasted it here: https://pastebin.com/HmqTkFtQ

Please help, I'm not sure why it will not record any player's time played for some reason.

Sponge: 1.12.2-7.3.0 
SpongeForge: 1.12.2-2838-7.3.0
Minecraft Forge: 14.23.5.2847
Minecraft: 1.12.2
PlayTimeCounter: v1.2

**Comment by TheBrokenDown** [comment]
Hey @NovaLynxie,

Do you have Nucleus plugin installed? As I remember, PlayTimeCounter uses Nucleus plugin to check if a player is AFK or not.

**Comment by NovaLynxie** [comment]
Yes, I do have Nucleus installed. I am using version 2.3.0 of the nucleus plugin.

**Comment by TheBrokenDown** [comment]
@NovaLynxie thanks for providing Nucleus version. I will check why PlayTimeCounter doesn't work and release the fix ASAP.

**Comment by TheBrokenDown** [comment]
@NovaLynxie actually I've just checked it and it looks like in case the property countAFKTime in config is set to true, plugin works correctly. You can use this as workaround while I'm preparing the fix.

**Comment by NovaLynxie** [comment]
Huh... just had a look at my configs, I did indeed have that set to false. So if I set countAFKTime to true it should work?

**Comment by TheBrokenDown** [comment]
@NovaLynxie yep, try to change it to true for some time.

**Comment by NovaLynxie** [comment]
Alright, will try that and see if it works.

**Comment by NovaLynxie** [comment]
Yep, that seems to have got it working. Errors in console have also stopped, am now getting a proper time value for playtime when command is typed.

**Comment by TheBrokenDown** [comment]
@NovaLynxie I have just fixed the problem. Please, download the new version of the plugin. https://github.com/TheBrokenDown/PlayTimeCounter/releases/tag/v1.3

**Comment by NovaLynxie** [comment]
Just updated to v1.3 and have set countAFKTime to false to test it, looks like its working now. Thanks again 😄
